### PR TITLE
2.2.0 Added Rotation & GroundAnchor to Marker & Bearing & Viewing angle to Mapview

### PR DESCRIPTION
**Pull request by yozef**
Added Rotation & GroundAnchor to Map Marker & Bearing & Viewing angle
to Map View

### CODE REVIEW

**Comment by yozef** [comment]
Forgot to add the `complete` event which is fired when the Map loads all the visible Tiles (mapViewDidFinishTileRendering).

**Comment by hansemannn** [comment]
Hey @yozef, can you check the latest [2.2.0](https://github.com/hansemannn/ti.googlemaps/releases/tag/v2.2.0) release? I just finished the testing and merged the commits from the last weeks into master. The changes also include the latest GoogleMaps.framework and `groundOffset` support. So can you add the new properties to the `TiGoogleMapsAnnotationProxy` from now on? The old one is deprecated since 2.2.0. Thank you! 😊

**Comment by yozef** [comment]
Will do, I'll update to your latest & do any modifications. Should be done by end of day today (EST).

**Comment by hansemannn** [comment]
Thanks!

**Pull request closed without merging**
