### PR TITLE
Support for map tiles, expose the "infoWindow" property, expose the Directions API

### PR DESCRIPTION
**Pull request by hansemannn**
- [x] Expose the `Tile` API
- [x] Expose `infoWindow` property in the `Annotation` class
- [x] Expose the `Directions API` by building an own client factory for the GMS REST API

### CODE REVIEW

**Comment by yozef** [comment]
Tried it with an image in a url structure on my web host, not 100% sure on usage use-case, though I was able to see the image (repeated for a 1/1/1.png)

**Comment by hansemannn** [comment]
@yozef the url tiles are meant for web-services that provide the tiles dynamically (e.g. the linked open street-map - see the example file).

**Comment by hansemannn** [comment]
@yozef I also just exposed the [Directions API](https://developers.google.com/maps/documentation/directions/intro?hl=de#Waypoints), wanted to try around with `NSURLSession` :-)

**Comment by yozef** [comment]
Been trying to figure out a way to display the polyline points, example:
`"polyline": {
                "points": "a}dcF~nchVPLXLHQhAsCDKzAyDPe@fAqC`@aAh@sARc@pCoHJUj@yAj@{AL]`@cAd@iAbAiCnC_HjAsCvAqDL_@l@mB`@sA^kAJ[h@aBPi@DSJWDMHSFS@GXaABIBI\\eAHW?ATy@HSPo@"
              },`

into : `[long, lat], [long, lat]...`

and I found this lib to do so: https://github.com/mapbox/polyline which works

**Comment by hansemannn** [comment]
Exposed the `decodePolylinePoints` method.

**Comment by hansemannn** [comment]
@yozef Sorry for making this PR so big, but I just refactored the methods to use an own request factory to be more flexible for more rest api calls :-) Basically, we are now able to call every Google Maps API request simply by using:
```objc
    TiGMSHTTPClient *httpClient = [[TiGMSHTTPClient alloc] initWithApiKey:apiKey];
    [httpClient loadWithRequestPath:@"directions/json"
                         andOptions:options
                  completionHandler:^(NSDictionary *json, NSError *error) {
                      // Handle json and error, that's it!
                  }];
```

**Pull request merged**
