### PR TITLE
Update GoogleMaps iOS to 2.0.1

### PR DESCRIPTION
**Pull request by hansemannn**
Currently only replaced the SDK's, referenced them and bumped the version. Some API's are not working, yet (probably because of the way being included). @yozef can you check?

🔥 Work in progress 🔥

### CODE REVIEW

**Comment by yozef** [comment]
While trying to compile the module, I get the Segmentation fault: 11 issue (https://jira.appcelerator.org/browse/TIMOB-23671)

I think this got solved in Ti 5.4.0, if I'm not mistaken. I will update the titanium.xcconfig to compile with 5.4.0 & update this comment.

**Comment by hansemannn** [comment]
I didn't even try building, yet. I don't think it can be compiled, yet. Simply because some classes cannot be found (`GMSPlace` and `GMSAutocompleteViewController`). No idea for now ...

**Comment by yozef** [comment]
I have a feeling some of these classes have been split into different (smaller) frameworks (after Google has split the Framework into 3 frameworks).. though the Class "names" should not have changed, maybe the #import of these classes needs to point to the new framework that has these classes. (import statements)... however I tried tinkering with that :-p

**Comment by hansemannn** [comment]
Got it, it's inside the `GooglePlaces` SDK now, commit coming.

**Comment by hansemannn** [comment]
@yozef please test

**Comment by yozef** [comment]
will do ;)

**Comment by hansemannn** [comment]
Works for me, except the autocomplete-search that needs a new API to configure the Places API-Key (that is now different to the one used for Maps).

**Comment by yozef** [comment]
~~~
[TRACE] [xcode-dist] ** BUILD SUCCEEDED **
[TRACE] [xcode-sim] ** BUILD SUCCEEDED **
[INFO]  Creating module zip
/usr/local/lib/node_modules/titanium/node_modules/longjohn/dist/longjohn.js:194
        throw e;
              ^
Error: ENOENT, no such file or directory '/Users/Yozef/Documents/ti.googlemaps/ios/platform/GoogleMapsBase.framework/Resources'
    at Error (native)
...
~~~

**Comment by hansemannn** [comment]
Yep, you have to build with `appc ti build -p ios --build-only` for SDK 5.2.2.GA and later. I just fixed the autocompletion (was just not enabled online, the module throws an error for that). New version coming now, upload with ~ 200MB takes a bit.

**Comment by hansemannn** [comment]
Approved!

**Pull request merged**
